import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on('console', (m) => console.log('[console]', m.type(), m.text()));
page.on('pageerror', (e) => console.log('[pageerror]', e.message));
await page.goto('http://localhost:5179/admin', { waitUntil: 'load' });
const refuser = page.getByText('TOUT REFUSER', { exact: false }).first();
if (await refuser.count()) await refuser.click();
await page.waitForTimeout(300);
const porteCA = page.getByText(/CA \(CONSEIL D.ADMIN/i).first();
await porteCA.waitFor({ timeout: 10000 });
await porteCA.locator('xpath=ancestor::button[1]').getByText('ENTRER').click();
await page.waitForTimeout(1000);
console.log('--- APRES CLIC PORTE ---');
console.log((await page.evaluate(() => document.body.innerText)).slice(0, 1500));
await page.screenshot({ path: '/Users/lesalondesinconnus/Documents/Websites/FMM 2026/captures/plan-marche/debug-apres-porte.png', fullPage: true });

await page.goto('http://localhost:5179/admin/planMarche', { waitUntil: 'load' });
await page.waitForTimeout(2000);
console.log('--- PLAN MARCHE ---');
console.log((await page.evaluate(() => document.body.innerText)).slice(0, 2000));
await page.screenshot({ path: '/Users/lesalondesinconnus/Documents/Websites/FMM 2026/captures/plan-marche/debug-planmarche.png', fullPage: true });
await browser.close();
