// Marché kiosks: single source of truth.
// Consumed by:
//   • src/pages/MarchePage.tsx          (public 3-tier showcase)
//   • src/firebase/mockApplications.ts  (CRM dashboard mock seed)
//
// Adding a kiosk here makes it appear in both places automatically.
// `tier: 'premium'` puts the artisan in the gold-rim pavilion at the top.
// `tier: 'marche'`  goes into the interactive grid below.
// `tier: 'digital'` goes into the Boutique Digitale band.

export type KioskTier = 'premium' | 'marche' | 'digital';

export interface MarcheKiosk {
  /** Stable id used as the mock vendor uid (e.g. `mock-v-artisans-azure`). */
  id: string;
  /** Public display name. */
  name: string;
  /** Where this kiosk shows up on the public page. */
  tier: KioskTier;
  /** Real contact name, used by the CRM "Contact" column. */
  contact: string;
  /** Real or placeholder email, only used by the CRM. */
  email: string;
  /** Free-text category badge (Cuir, Bijoux, Forge…). */
  category: string;
  /** Short tagline shown on the marché grid card (1 line). */
  tagFR: string;
  tagEN: string;
  /** Long bio shown when the card is featured or expanded. */
  bioFR?: string;
  bioEN?: string;
  /** Hero image path under /public/. */
  image?: string;
  /** Optional crop hint for object-position. */
  imagePosition?: string;
  /** Where their shop / IG / FB lives (main CTA). */
  href?: string;
  /** Liens sociaux distincts, affichés en petites pastilles sous le CTA. */
  website?: string;
  facebook?: string;
  instagram?: string;
  /** Emplacement payé (10x10, 10x20, 10x30, Faubourg). Info CRM, pas affiché. */
  booth?: string;
  /** Optional CTA label override for premium tier. */
  cta?: { FR: string; EN: string };
  /** Promo code applicable to this digital boutique. */
  promo?: string;
  /** Éditions où ce kiosque a tenu place. Sert au filtre par année de
      la grille. Absent = édition courante par défaut. */
  years?: number[];
}

/* ─── Premium pavilion ───────────────────────────────────────────────
   Édition 2026 (source : export Zeffy « Kiosques 2026 », 30 août 2026).
   Les fanions : les plus grands emplacements et les artisans qui
   reviennent d'année en année. `contact` = la personne inscrite sur
   Zeffy; `email` reste un jeton (le vrai courriel vit dans le CRM). */
export const PREMIUM_VENDORS: MarcheKiosk[] = [
  {
    id: 'artisans-azure',
    name: 'Les Artisans d’Azure',
    tier: 'premium',
    contact: 'Samuel Gagnon-Tremblay',
    email: 'contact@artisans-azure.example.ca',
    category: 'Cuir & Armures',
    tagFR: 'Armures et accessoires de cuir',
    tagEN: 'Leather armour & accessories',
    bioFR: 'Fleuron de la confection québécoise, les produits Artisans d’Azure sont conçus par des GNistes, pour des GNistes. Une attention particulière à la durabilité et à la praticité : armures et accessoires de cuir, vêtements haut de gamme ou personnalisés, armures composites de métal et de cuir.',
    bioEN: 'A jewel of Quebec craftsmanship, Artisans d’Azure products are designed by LARPers, for LARPers. Special attention to durability and practicality: leather armour and accessories, premium and custom garments, composite metal-and-leather armour.',
    image: '/wix/marche/2c7e6c33.jpg',
    href: 'https://artisansdazure.com/',
    facebook: 'https://www.facebook.com/artisansdazure',
    instagram: 'https://www.instagram.com/artisansdazure',
    booth: '10x20',
    years: [2025, 2026],
  },
  {
    id: 'zardwin',
    name: 'Zardwin',
    tier: 'premium',
    contact: 'Maxime Pocius',
    email: 'contact@zardwin.example.ca',
    category: 'Cuir & Armures',
    tagFR: 'Cuir et armures pour le Grandeur Nature',
    tagEN: 'Leather and armour for LARP',
    bioFR: 'Zardwin coud des armures, des vêtements et des accessoires de cuir pour le Grandeur Nature depuis plus de vingt ans, à Longueuil. Maxime Pocius a commencé par fabriquer son propre équipement de joueur; la boutique fournit aujourd’hui des foires Renaissance et des partenaires comme Calimacil.',
    bioEN: 'Zardwin has been sewing leather armour, garments and accessories for LARP for more than twenty years, out of Longueuil. Maxime Pocius started by making his own player gear; the shop now supplies Renaissance fairs and partners such as Calimacil.',
    image: '/marche/2026/zardwin.webp',
    href: 'https://zardwin.ca/',
    facebook: 'https://www.facebook.com/zardwinboutiquegn/',
    booth: '10x20',
    years: [2026],
  },
  {
    id: 'cuir-du-nord',
    name: 'Atelier Cuir du Nord',
    tier: 'premium',
    contact: 'Jonathan Guay',
    email: 'contact@cuir-du-nord.example.ca',
    category: 'Cuir & Armures',
    tagFR: 'Cuir viking et reconstitution historique',
    tagEN: 'Viking leather and historical reenactment',
    bioFR: 'L’Atelier Cuir du Nord travaille le cuir à Saint-Vallier depuis plus de seize ans, pour la reconstitution historique autant que pour des pièces d’aujourd’hui. L’atelier s’inspire du monde scandinave et touche aussi au bois, au métal et au textile.',
    bioEN: 'Atelier Cuir du Nord has worked leather in Saint-Vallier for over sixteen years, for historical reenactment as much as for modern pieces. The workshop draws on the Scandinavian world and also works wood, metal and textile.',
    image: '/marche/2026/cuir-du-nord.webp',
    href: 'https://www.facebook.com/CuirduNord/',
    booth: '10x30',
    years: [2026],
  },
  {
    id: 'druide-diamant-lune',
    name: 'Le druide et Diamant de Lune',
    tier: 'premium',
    contact: 'Krystel Marenger',
    email: 'contact@druide-diamant-lune.example.ca',
    category: 'Bijoux & Pierres',
    tagFR: 'Pierres, herbes et créations rituelles',
    tagEN: 'Stones, herbs and ritual creations',
    bioFR: 'Diamant de Lune est la boutique ésotérique de Krystel Marenger, à Gatineau. Les tablettes se remplissent de pierres, d’herbes et de créations rituelles, avec de nouvelles pièces presque chaque semaine.',
    bioEN: 'Diamant de Lune is Krystel Marenger’s esoteric shop in Gatineau. The shelves fill up with stones, herbs and ritual creations, with new pieces almost every week.',
    image: '/marche/2026/druide-diamant-lune.webp',
    href: 'https://www.diamantdelune.ca/',
    facebook: 'https://www.facebook.com/p/Diamant-de-Lune-100064738939187/',
    instagram: 'https://www.instagram.com/boutique.diamant.de.lune/',
    booth: '10x20',
    years: [2026],
  },
  {
    id: 'mandragores',
    name: 'L’Atelier des Mandragores',
    tier: 'premium',
    contact: 'Annie Savard-Filion',
    email: 'contact@mandragores.example.ca',
    category: 'Soins & Savons',
    tagFR: 'Savons et parfums botaniques faits à Montréal',
    tagEN: 'Botanical soaps and perfumes made in Montreal',
    bioFR: 'Annie Savard-Filion fabrique ses parfums et ses savons dans son atelier de Rosemont, à Montréal, avec des huiles essentielles et des ingrédients naturels. Elle puise dans le monde des plantes et dans l’imaginaire des légendes.',
    bioEN: 'Annie Savard-Filion makes her perfumes and soaps in her Rosemont workshop in Montreal, with essential oils and natural ingredients. She draws on the world of plants and on the imagery of legend.',
    image: '/wix/marche/5b12ccf8.jpg',
    href: 'https://atelierdesmandragores.ca/',
    facebook: 'https://www.facebook.com/atelierdesmandragores/',
    instagram: 'https://www.instagram.com/atelierdesmandragores',
    booth: '10x10',
    years: [2025, 2026],
  },
];

/* ─── Marché: interactive kiosk grid ────────────────────────────────
   Un kiosque qui revient garde sa fiche et cumule ses `years`.
   Sans photo trouvée, la tuile porte le blason du festival
   (`/marche/2026/_fmm.webp`) : à remplacer dès que l'artisan envoie la
   sienne (admin › Marchands). Décision d'Alex, 30 août 2026. */
export const MARCHE_VENDORS: MarcheKiosk[] = [
  {
    id: 'panassor',
    name: 'Panassor',
    tier: 'marche',
    contact: 'Charles Blain',
    email: 'contact@panassor.example.ca',
    category: 'Cuir & Armures',
    tagFR: 'Kits médiévaux évolutifs pour le GN',
    tagEN: 'Evolving medieval kits for LARP',
    bioFR: 'Panassor fabrique au Québec des kits médiévaux pensés pour le Grandeur Nature, le jeu de rôle et les passionnés d’histoire. Charles Blain conçoit chaque équipement pour qu’il grandisse avec son joueur, une pièce à la fois.',
    bioEN: 'Panassor makes medieval kits in Quebec for LARP, roleplaying and history enthusiasts. Charles Blain designs each set to grow with its player, one piece at a time.',
    image: '/marche/2026/panassor.webp',
    href: 'https://www.panassor.ca/',
    booth: '10x20',
    years: [2026],
  },
  {
    id: 'griffe-dragon-noir',
    name: 'La griffe du dragon noir',
    tier: 'marche',
    contact: 'Sébastien Baril',
    email: 'contact@griffe-dragon-noir.example.ca',
    category: 'Cuir & Armures',
    tagFR: 'Cuir médiéval et fantastique, sur mesure',
    tagEN: 'Medieval and fantasy leather, made to order',
    bioFR: 'Sébastien Baril travaille le cuir depuis une quinzaine d’années et en tire des armures et des accessoires d’inspiration médiévale et fantastique. La griffe du dragon noir vend des pièces prêtes à porter et prend aussi les commandes sur mesure.',
    bioEN: 'Sébastien Baril has worked leather for some fifteen years, shaping armour and accessories with a medieval and fantasy bent. La griffe du dragon noir sells ready-to-wear pieces and takes custom orders too.',
    image: '/marche/2026/griffe-dragon-noir.webp',
    href: 'https://www.griffemedievale.com/',
    facebook: 'https://www.facebook.com/griffedudragonnoir',
    instagram: 'https://www.instagram.com/griffe.du.dragon.noir/',
    booth: '10x20',
    years: [2026],
  },
  {
    id: 'rose-dragon',
    name: 'La Rose et le Dragon',
    tier: 'marche',
    contact: 'Hélène Cayouette',
    email: 'contact@rose-dragon.example.ca',
    category: 'Vêtements & Coiffes',
    tagFR: 'Boutique médiévale de Drummondville',
    tagEN: 'Drummondville’s medieval shop',
    bioFR: 'La Rose et le Dragon, tenue par Hélène Cayouette à Saint-Germain-de-Grantham, a ouvert la première boutique médiévale de la région de Drummondville. Robes, pourpoints, bijoux, armures et épées y côtoient un atelier de couture sur mesure et un service de location de costumes.',
    bioEN: 'La Rose et le Dragon, run by Hélène Cayouette in Saint-Germain-de-Grantham, opened the first medieval shop in the Drummondville area. Dresses, doublets, jewellery, armour and swords sit alongside a custom tailoring workshop and costume rentals.',
    image: '/marche/2026/rose-dragon.webp',
    href: 'https://www.facebook.com/La-Rose-et-le-Dragon-349231708430383/',
    booth: '10x20',
    years: [2025, 2026],
  },
  {
    id: 'artisans-monde',
    name: 'Les Artisans du Monde',
    tier: 'marche',
    contact: 'Mathias Tremblay',
    email: 'contact@artisans-monde.example.ca',
    category: 'Cuir & Armures',
    tagFR: 'Peaux, fourrures et boucliers pour le GN',
    tagEN: 'Hides, furs and shields for LARP',
    bioFR: 'Les Artisans du Monde réunissent des artisans d’ici qui fabriquent des peaux, des fourrures, des boucliers et des vêtements pour le Grandeur Nature. Mathias Tremblay met de l’avant des pièces uniques, taillées à la mesure de chaque joueur.',
    bioEN: 'Les Artisans du Monde bring together local makers of hides, furs, shields and clothing for LARP. Mathias Tremblay puts forward one-of-a-kind pieces, cut to fit each player.',
    image: '/wix/marche/ec6cf71c.jpg',
    href: 'https://lesartisansdumonde.net',
    facebook: 'https://www.facebook.com/profile.php?id=100090002331524',
    instagram: 'https://www.instagram.com/lesartisansdumondeinsta/',
    booth: '10x20',
    years: [2025, 2026],
  },
  {
    id: 'emielie-evilnut',
    name: 'éMielie Créations & Evilnut Créations',
    tier: 'marche',
    image: '/marche/2026/_fmm.webp',
    contact: 'Emilie Guertin Lavictoire',
    email: 'contact@emielie-evilnut.example.ca',
    category: 'Créations',
    tagFR: 'Créations artisanales',
    tagEN: 'Handmade creations',
    booth: '10x20',
    years: [2026],
  },
  {
    id: 'crazy-kali',
    name: 'Créations Crazy Kali',
    tier: 'marche',
    contact: 'Marilyn Gagné',
    email: 'contact@crazy-kali.example.ca',
    category: 'Créations',
    tagFR: 'Créations artisanales',
    tagEN: 'Handmade creations',
    image: '/marche/2026/crazy-kali.webp',
    href: 'https://www.facebook.com/people/Cr%C3%A9ations-Crazy-Kali/100054412932761/',
    booth: '10x20',
    years: [2026],
  },
  {
    id: 'la-bohemienne',
    name: 'La Bohémienne',
    tier: 'marche',
    image: '/marche/2026/_fmm.webp',
    contact: 'Marie Claude Seney',
    email: 'contact@la-bohemienne.example.ca',
    category: 'Créations',
    tagFR: 'Créations artisanales',
    tagEN: 'Handmade creations',
    booth: '10x20',
    years: [2026],
  },
  {
    id: 'etalon-pierre-lune',
    name: 'L’Étalon Pierre de Lune',
    tier: 'marche',
    image: '/marche/2026/_fmm.webp',
    contact: 'Stephanie Corbin',
    email: 'contact@etalon-pierre-lune.example.ca',
    category: 'Bijoux & Pierres',
    tagFR: 'Pierres et cristaux',
    tagEN: 'Stones and crystals',
    booth: '10x20',
    years: [2026],
  },
  {
    id: 'geeksfaction',
    name: 'Les Productions Geeksfaction',
    tier: 'marche',
    contact: 'Carl Jacques',
    email: 'contact@geeksfaction.example.ca',
    category: 'Créations',
    tagFR: 'Vêtements et objets geek imprimés',
    tagEN: 'Printed geek clothing and goods',
    bioFR: 'Les Productions Geeksfaction impriment des t-shirts, des capuchons et d’autres objets tirés de la culture geek et fantastique, sous la bannière Geek-Art-Studio. Carl Jacques y ajoute sa photographie et ses critiques de jeux.',
    bioEN: 'Les Productions Geeksfaction print t-shirts, hoodies and other goods drawn from geek and fantasy culture, under the Geek-Art-Studio banner. Carl Jacques adds his photography and game reviews to the mix.',
    image: '/marche/2026/geeksfaction.webp',
    href: 'https://geekartstudio.com',
    facebook: 'https://www.facebook.com/geeksfaction/',
    instagram: 'https://www.instagram.com/geeksfaction/',
    booth: '10x20',
    years: [2026],
  },
  {
    id: 'frek-atelier',
    name: 'Frek Atelier',
    tier: 'marche',
    contact: 'Erika Navia',
    email: 'contact@frek-atelier.example.ca',
    category: 'Vêtements & Coiffes',
    tagFR: 'Fourrure recyclée, pièces sur mesure',
    tagEN: 'Recycled fur, custom pieces',
    bioFR: 'Frek Atelier redonne vie à la fourrure recyclée depuis son atelier de l’avenue du Parc, à Montréal. Erika Navia et Keven Lemonnier transforment de vieux manteaux en accessoires, en vêtements et en pièces de décoration cousus à la main.',
    bioEN: 'Frek Atelier gives recycled fur a second life from its workshop on Avenue du Parc in Montreal. Erika Navia and Keven Lemonnier turn old coats into hand-sewn accessories, garments and decor pieces.',
    image: '/wix/marche/f7025e55.jpg',
    href: 'https://www.frekatelier.com/',
    facebook: 'https://www.facebook.com/p/FrekAtelier-100063832154396/',
    instagram: 'https://www.instagram.com/frekatelier/',
    booth: '10x10',
    years: [2025, 2026],
  },
  {
    id: 'delices-erabeille',
    name: 'Délices Érabeille',
    tier: 'marche',
    contact: 'Jean-Claude Pelletier',
    email: 'contact@delices-erabeille.example.ca',
    category: 'Miel & Douceurs',
    tagFR: 'Caramels et gelées à l’érable et au miel',
    tagEN: 'Maple and honey caramels and jellies',
    bioFR: 'Délices Érabeille transforme le miel et le sirop d’érable du Québec depuis 2002, dans son atelier de Mascouche. Jean-Claude Pelletier en tire des caramels, des gelées et des sauces, à partir de miel et d’érable purs, non pasteurisés.',
    bioEN: 'Délices Érabeille has turned Quebec honey and maple syrup into treats since 2002, from its workshop in Mascouche. Jean-Claude Pelletier makes caramels, jellies and sauces with pure, unpasteurized honey and maple.',
    image: '/marche/2026/delices-erabeille.webp',
    booth: '10x10',
    years: [2026],
  },
  {
    id: 'miel-morand',
    name: 'Miel Morand',
    tier: 'marche',
    contact: 'Serge Morand',
    email: 'contact@miel-morand.example.ca',
    category: 'Miel & Douceurs',
    tagFR: 'Miel et hydromel de Saint-Thomas',
    tagEN: 'Honey and mead from Saint-Thomas',
    bioFR: 'Miel Morand élève ses ruches à Saint-Thomas, dans Lanaudière, depuis plus de quarante ans. Serge Morand y produit du miel, des condiments au miel et quatre hydromels médaillés à la Coupe des Nations.',
    bioEN: 'Miel Morand has kept bees in Saint-Thomas, in Lanaudière, for more than forty years. Serge Morand produces honey, honey condiments and four meads that took medals at the Coupe des Nations.',
    image: '/marche/2026/miel-morand.webp',
    href: 'https://mielmorand.com',
    facebook: 'https://www.facebook.com/mielmorand/',
    booth: '10x10',
    years: [2026],
  },
  {
    id: 'corpsage',
    name: 'CorpSage Henna',
    tier: 'marche',
    contact: 'Turkoize Lemay Dostie',
    email: 'contact@corpsage.example.ca',
    category: 'Soins & Savons',
    tagFR: 'Henné naturel, art éphémère sur la peau',
    tagEN: 'Natural henna, ephemeral art on skin',
    bioFR: 'CorpSage, c’est Turkoize, une artiste multidisciplinaire qui a découvert le henné en 2017 pendant une collecte de fonds en Inde. Elle applique aujourd’hui un henné brun entièrement naturel, quelque part entre le tatouage éphémère et le rituel.',
    bioEN: 'CorpSage is Turkoize, a multidisciplinary artist who discovered henna in 2017 while fundraising in India. She now applies fully natural brown henna, somewhere between a temporary tattoo and a ritual.',
    image: '/wix/marche/2de271eb.jpg',
    href: 'https://corpsage.com/',
    facebook: 'https://www.facebook.com/corpsagehennatatouage/',
    instagram: 'https://www.instagram.com/corpsage_henna_tattoo/',
    booth: '10x10',
    years: [2025, 2026],
  },
  {
    id: 'bijouxstensile',
    name: 'Bijoux’stensile',
    tier: 'marche',
    contact: 'Natalie Cofsky',
    email: 'contact@bijouxstensile.example.ca',
    category: 'Bijoux & Pierres',
    tagFR: 'Vieille coutellerie transformée en bijoux',
    tagEN: 'Old flatware turned into jewellery',
    bioFR: 'Bijoux’stensile, à Sainte-Julienne, redonne une vie à la vieille coutellerie en argent plaqué et en inox. Natalie Cofsky et Sylvain Lafond transforment fourchettes et cuillères en bijoux et en objets du quotidien.',
    bioEN: 'Bijoux’stensile, in Sainte-Julienne, gives old silver-plated and stainless flatware a second life. Natalie Cofsky and Sylvain Lafond turn forks and spoons into jewellery and everyday objects.',
    image: '/marche/2026/bijouxstensile.webp',
    href: 'https://www.facebook.com/Bijouxstensile',
    booth: '10x10',
    years: [2026],
  },
  {
    id: 'shadow-volva',
    name: 'Shadow la Völva',
    tier: 'marche',
    contact: 'Marie-Claude Venne',
    email: 'contact@shadow-volva.example.ca',
    category: 'Tarot & Oracles',
    tagFR: 'Créations d’inspiration nordique',
    tagEN: 'Nordic-inspired creations',
    image: '/marche/2026/shadow-volva.webp',
    href: 'https://www.facebook.com/profile.php?id=61559324510781',
    booth: '10x10',
    years: [2026],
  },
  {
    id: 'dark-amazon',
    name: 'Créations Dark Amazon',
    tier: 'marche',
    contact: 'Marie-Soleil Dufresne',
    email: 'contact@dark-amazon.example.ca',
    category: 'Vêtements & Coiffes',
    tagFR: 'Coiffes faites main et pièces sur mesure',
    tagEN: 'Handmade headdresses and custom pieces',
    bioFR: 'Marie-Soleil Dufresne fabrique des coiffes à la main, à Saint-Barthélemy. Elle prend aussi des commandes spéciales pour des pièces sur mesure.',
    bioEN: 'Marie-Soleil Dufresne makes headdresses by hand in Saint-Barthélemy. She also takes special orders for custom pieces.',
    image: '/marche/2026/dark-amazon.webp',
    href: 'https://www.facebook.com/profile.php?id=100062978151371',
    booth: '10x10',
    years: [2026],
  },
  {
    id: 'brigitte-leonard',
    name: 'Tarologue Brigitte Léonard',
    tier: 'marche',
    contact: 'Brigitte Léonard',
    email: 'contact@brigitte-leonard.example.ca',
    category: 'Tarot & Oracles',
    tagFR: 'Tirages de tarot de Marseille',
    tagEN: 'Marseille tarot readings',
    bioFR: 'Brigitte Léonard est tarologue certifiée, installée à Notre-Dame-de-la-Salette, dans l’Outaouais. Elle tire le tarot de Marseille et pratique la numérologie, en personne ou à distance.',
    bioEN: 'Brigitte Léonard is a certified tarot reader based in Notre-Dame-de-la-Salette, in the Outaouais. She reads the Marseille tarot and practises numerology, in person or remotely.',
    image: '/marche/2026/brigitte-leonard.webp',
    href: 'https://www.tarologie-conseil-brigitteleonard.com/',
    facebook: 'https://www.facebook.com/BrigitteTarologue/',
    booth: '10x10',
    years: [2026],
  },
  {
    id: 'luna-savonnerie',
    name: 'Luna Savonnerie',
    tier: 'marche',
    contact: 'Melissa Thibert',
    email: 'contact@luna-savonnerie.example.ca',
    category: 'Soins & Savons',
    tagFR: 'Savons et soins faits main, en petites quantités',
    tagEN: 'Handmade soaps and body care, small batches',
    bioFR: 'Luna Savonnerie fabrique à la main des savons et des soins pour le corps et le visage, en petites quantités. L’entreprise familiale choisit ses ingrédients en pensant à la santé de ses clients et à l’environnement.',
    bioEN: 'Luna Savonnerie hand-makes soaps and body and facial care in small batches. The family business picks its ingredients with its customers’ health and the environment in mind.',
    image: '/marche/2026/luna-savonnerie.webp',
    href: 'https://www.lunasavonnerie.com/',
    facebook: 'https://www.facebook.com/Lunasavonnerie',
    instagram: 'https://www.instagram.com/lunasavonnerie/',
    booth: '10x10',
    years: [2026],
  },
  {
    id: 'lotus-aw',
    name: 'Lotus AW',
    tier: 'marche',
    contact: 'Amélie Whissell',
    email: 'contact@lotus-aw.example.ca',
    category: 'Soins & Savons',
    tagFR: 'Reiki et soins énergétiques',
    tagEN: 'Reiki and energy care',
    bioFR: 'Amélie Whissell offre des soins énergétiques à Notre-Dame-de-la-Paix, dans l’Outaouais : reiki, harmonisation Atlane, massage crânien indien et libération des chakras. Elle accompagne les gens vers un équilibre physique et émotionnel qui dure.',
    bioEN: 'Amélie Whissell offers energy care in Notre-Dame-de-la-Paix, in the Outaouais: reiki, Atlane harmonization, Indian head massage and chakra release. She walks people toward a physical and emotional balance that lasts.',
    image: '/marche/2026/lotus-aw.webp',
    href: 'https://www.lotusaw.com/',
    facebook: 'https://www.facebook.com/Lotus-AW-1622485394515155',
    booth: '10x10',
    years: [2026],
  },
  {
    id: 'isabelle-jewelry',
    name: 'Les bijoux de mailles et d’écailles d’Isabelle',
    tier: 'marche',
    contact: 'Isabelle Robert',
    email: 'contact@isabelle-jewelry.example.ca',
    category: 'Bijoux & Pierres',
    tagFR: 'Bijoux en mailles et écailles de métal',
    tagEN: 'Chainmail and scale mail jewellery',
    bioFR: 'Isabelle Robert tisse ses bijoux à partir de mailles et d’écailles de métal, la technique même de la cotte de mailles. Chaque pièce part d’anneaux assemblés un à un, à la main.',
    bioEN: 'Isabelle Robert weaves her jewellery from metal rings and scales, the very technique of chainmail. Each piece starts with rings joined one by one, by hand.',
    image: '/marche/2026/isabelle-jewelry.webp',
    href: 'https://www.facebook.com/Isabellesjewelry',
    booth: '10x10',
    years: [2025, 2026],
  },
  {
    id: 'cuir-arcana',
    name: 'Cuir Arcana',
    tier: 'marche',
    contact: 'Tanya Grenon',
    email: 'contact@cuir-arcana.example.ca',
    category: 'Cuir & Armures',
    tagFR: 'Cuir façonné pièce par pièce, jamais reproduit',
    tagEN: 'Leather shaped piece by piece, never repeated',
    bioFR: 'Tanya Grenon travaille le cuir depuis 2013 sous le nom Cuir Arcana. Elle ne reproduit jamais deux fois la même pièce et ne copie le travail de personne.',
    bioEN: 'Tanya Grenon has worked leather since 2013 under the name Cuir Arcana. She never makes the same piece twice and copies no one’s work.',
    image: '/wix/marche/b4c19724.webp',
    href: 'https://www.cuirarcana.ca/',
    booth: '10x10',
    years: [2025, 2026],
  },
  {
    id: 'raven-vinland',
    name: 'Raven from Vinland',
    tier: 'marche',
    image: '/marche/2026/_fmm.webp',
    contact: 'François Chaput',
    email: 'contact@raven-vinland.example.ca',
    category: 'Créations',
    tagFR: 'Artisanat d’inspiration viking',
    tagEN: 'Viking-inspired craft',
    booth: '10x10',
    years: [2026],
  },
  {
    id: 'mama-rose-quartz',
    name: 'Mama Rose Quartz',
    tier: 'marche',
    contact: 'Émilie Maloney',
    email: 'contact@mama-rose-quartz.example.ca',
    category: 'Bijoux & Pierres',
    tagFR: 'Bijoux et talismans en pierres semi-précieuses',
    tagEN: 'Gemstone jewellery and talismans',
    bioFR: 'Émilie Maloney importe des pierres semi-précieuses et les monte en bijoux et en talismans depuis 2021, en Mauricie. Bracelets, colliers et pièces en macramé sortent de l’atelier Mama Rose Quartz.',
    bioEN: 'Émilie Maloney has imported semi-precious stones and set them into jewellery and talismans since 2021, in the Mauricie region. Bracelets, necklaces and macramé pieces come out of the Mama Rose Quartz studio.',
    image: '/wix/marche/73932437.jpg',
    href: 'https://www.mamarosequartz.ca/',
    booth: '10x10',
    years: [2025, 2026],
  },
  {
    id: 'creations-eau-lo',
    name: 'Les Créations de l’eau lo',
    tier: 'marche',
    image: '/marche/2026/_fmm.webp',
    contact: 'Karine Pascale Poirier',
    email: 'contact@creations-eau-lo.example.ca',
    category: 'Créations',
    tagFR: 'Bougies artisanales à la cire de soya',
    tagEN: 'Handmade soy wax candles',
    bioFR: 'Les Créations de l’eau lo coulent des bougies à la cire de soya et de paraffine, vendues directement sur Instagram.',
    bioEN: 'Les Créations de l’eau lo pour soy and paraffin wax candles, sold directly through Instagram.',
    href: 'https://www.instagram.com/les_creations_de_leau_lo/',
    booth: 'Faubourg',
    years: [2026],
  },
  {
    id: 'dancing-crow',
    name: 'The Dancing Crow',
    tier: 'marche',
    contact: 'Roxane de Grandpré',
    email: 'contact@dancing-crow.example.ca',
    category: 'Tarot & Oracles',
    tagFR: 'Tarot et dés peints à la main',
    tagEN: 'Tarot and hand-painted dice',
    bioFR: 'The Dancing Crow lit le tarot et peint des dés pour les jeux de rôle sur table, dans la région d’Ottawa et de Gatineau. Le kiosque est tenu par Roxane de Grandpré.',
    bioEN: 'The Dancing Crow reads tarot and paints dice for tabletop roleplaying games, in the Ottawa and Gatineau area. Roxane de Grandpré runs the stall.',
    image: '/marche/2026/dancing-crow.webp',
    href: 'https://linktr.ee/thedancingcrow',
    instagram: 'https://www.instagram.com/themdancingcrows/',
    booth: 'Faubourg',
    years: [2026],
  },
  {
    id: 'guylaine-periard',
    name: 'Guylaine Periard',
    tier: 'marche',
    image: '/marche/2026/_fmm.webp',
    contact: 'Guylaine Periard',
    email: 'contact@guylaine-periard.example.ca',
    category: 'Créations',
    tagFR: 'Artisanat du Faubourg',
    tagEN: 'Faubourg crafts',
    booth: 'Faubourg',
    years: [2026],
  },
  {
    id: 'violette-ink',
    name: 'Violette Ink',
    tier: 'marche',
    contact: 'Pamela Laviolette',
    email: 'contact@violette-ink.example.ca',
    category: 'Créations',
    tagFR: 'Tatouage fine ligne et peinture',
    tagEN: 'Fine-line tattoo and painting',
    bioFR: 'Pamela Laviolette peint et tatoue à Joliette sous le nom Violette Ink. Elle travaille surtout la ligne fine et partage ses toiles sur Instagram.',
    bioEN: 'Pamela Laviolette paints and tattoos in Joliette under the name Violette Ink. She works mostly in fine line and shares her canvases on Instagram.',
    image: '/marche/2026/violette-ink.webp',
    href: 'https://www.instagram.com/violette.ink/',
    facebook: 'https://www.facebook.com/Pamela.Laviolette/',
    booth: 'Faubourg',
    years: [2026],
  },
  {
    id: 'elija-orgonite',
    name: 'Elija Orgonite',
    tier: 'marche',
    contact: 'Martine Parent',
    email: 'contact@elija-orgonite.example.ca',
    category: 'Bijoux & Pierres',
    tagFR: 'Orgonites en résine et métal',
    tagEN: 'Resin and metal orgonite',
    bioFR: 'Martine Parent fabrique des orgonites sous le nom Elija Orgonite, des pièces de résine et de métal pensées pour l’équilibre énergétique. Elles se trouvent sur Etsy et sur sa page Facebook.',
    bioEN: 'Martine Parent makes orgonite under the name Elija Orgonite, resin and metal pieces made with energy balance in mind. They can be found on Etsy and on her Facebook page.',
    image: '/marche/2026/elija-orgonite.webp',
    href: 'https://elijaorgonite.etsy.com/',
    facebook: 'https://www.facebook.com/people/Elija-Orgonite/61577544696573/',
    booth: 'Faubourg',
    years: [2026],
  },
  {
    id: 'belles-trouvailles',
    name: 'Les belles trouvailles',
    tier: 'marche',
    image: '/marche/2026/_fmm.webp',
    contact: 'Jovette Matte',
    email: 'contact@belles-trouvailles.example.ca',
    category: 'Créations',
    tagFR: 'Trouvailles du Faubourg',
    tagEN: 'Faubourg finds',
    booth: 'Faubourg (2 kiosques)',
    years: [2026],
  },

  /* ── Archives 2025 : kiosques qui ne reviennent pas en 2026 ── */
  {
    id: 'chantelame-ariane',
    name: 'Forge Chantelame & Aux Fils d’Ariane',
    tier: 'marche',
    contact: 'Ariane Sigurdsdottir & Aslak Stormhammer',
    email: 'contact@chantelame-ariane.example.ca',
    category: 'Forge · Tissage',
    tagFR: 'Forge viking & atelier de tisserande',
    tagEN: 'Viking forge & weaver’s workshop',
    bioFR: 'Au fond des bois, au nord, loin de l’électricité et de la technologie, se trouve une Ger (yourte) avec une forge et un atelier de tisserande. Tendez bien l’oreille : si vous entendez « héhéhé comment ça va poto ! », c’est que vous avez trouvé le clan Viking Autonome d’Ariane et Aslak.',
    bioEN: 'Deep in the northern woods, far from electricity and tech, sits a yurt housing a forge and a weaving workshop. Listen for the friendly call: that’s how you’ll know you’ve found Ariane and Aslak’s Autonomous Viking Clan.',
    image: '/wix/marche/0b4c7ac8.jpg',
    years: [2025],
  },
  {
    id: 'forets-papilles',
    name: 'Forêts et Papilles',
    tier: 'marche',
    contact: 'Roxane Tessier',
    email: 'contact@forets-papilles.example.ca',
    category: 'Cueillette · Herboristerie',
    tagFR: 'Cueillette sauvage & savoirs ancestraux',
    tagEN: 'Wild foraging & ancestral wisdom',
    bioFR: 'Le bonheur est bien meilleur quand il est partagé. Forêts & Papilles, c’est une histoire de partage et de passion : transmettre l’amour de la nature et perpétuer les savoirs ancestraux de la cueillette sauvage.',
    bioEN: 'Happiness is better when shared. Forêts & Papilles is a story of sharing and passion: passing on a love of nature and the ancestral knowledge of wild foraging.',
    image: '/wix/marche/a2d1dca3.jpg',
    years: [2025],
  },
  { id: 'ferme-mouflon',     name: 'Ferme Mouflon',         tier: 'marche', contact: 'Famille Lavoie',   email: 'ferme@mouflon.example.ca',category: 'Élevage',      tagFR: 'Moutons Icelandic élevés au pâturage',  tagEN: 'Pasture-raised Icelandic sheep',     bioFR: 'Laine, peaux et produits issus d’un élevage Icelandic au pâturage.', bioEN: 'Wool, hides and products from pasture-raised Icelandic sheep.', href: 'https://fermemouflon.com/', image: '/wix/marche/0b69be84.jpg' , years: [2025] },
  { id: 'kissisam',          name: 'Pâtisserie Kîssisam',   tier: 'marche', contact: 'Naomi Wapachee',   email: 'kissisam@example.ca',     category: 'Restauration', tagFR: 'Pâtisseries inspirées de racines autochtones', tagEN: 'Pastries from Indigenous roots', bioFR: 'Pâtisseries fines inspirées de saveurs et techniques autochtones.', bioEN: 'Fine pastries inspired by Indigenous flavours and techniques.', href: 'https://www.kisisam.com/', image: '/wix/marche/5660e1a5.jpg' , years: [2025] },
  { id: 'argile-papier',     name: 'Argile de Papier',      tier: 'marche', contact: 'Clarisse Hébert', email: 'argile@papier.example.ca',category: 'Sculpture',    tagFR: 'Créations d’argile de papier',          tagEN: 'Paper-clay creations',               bioFR: 'Sculptures et objets décoratifs en argile de papier.', bioEN: 'Sculptures and decorative objects in paper clay.', image: '/wix/marche/c266478f.jpg' , years: [2025] },
  { id: 'editions-mondes',   name: 'Les Éditions Mondes Imaginaires', tier: 'marche', contact: 'Olivier Couture', email: 'editeur@mondesimaginaires.example.ca', category: 'Édition', tagFR: 'Maison d’édition',    tagEN: 'Indie publisher',                    bioFR: 'Romans, recueils et jeux de rôle d’univers imaginaires.', bioEN: 'Novels, anthologies and tabletop RPGs from imaginary worlds.', href: 'https://editionsmondesimaginaires.com/', image: '/wix/marche/97646275.jpg' , years: [2025] },
  { id: 'ciriers-allumes',   name: 'Les Ciriers Allumés',   tier: 'marche', contact: 'Marie-Élise Cyr',  email: 'cire@ciriersallumes.example.ca', category: 'Bougies',   tagFR: 'Cires et chandelles',                   tagEN: 'Wax and candles',                     bioFR: 'Bougies coulées à la main, cires d’abeille et de soya.', bioEN: 'Hand-poured candles in beeswax and soy.', image: '/wix/marche/89000880.jpg' , years: [2025] },
  { id: 'sol-art',           name: 'Sol Art',               tier: 'marche', contact: 'Solène Tanguay',   email: 'sol@solart.example.ca',   category: 'Art',          tagFR: 'Atelier & galerie d’art',               tagEN: 'Studio & gallery',                    bioFR: 'Atelier itinérant : peintures, dessins, illustrations.', bioEN: 'Travelling studio: paintings, drawings, illustrations.', href: 'https://www.ateliergaleriedartsolart.com/', image: '/wix/marche/36bb3314.jpg' , years: [2025] },
  { id: 'mont-vezeau',       name: 'Domaine Mont Vezeau',   tier: 'marche', contact: 'Jeanne Pellerin',  email: 'vignes@montvezeau.example.ca', category: 'Vinification', tagFR: 'Vins de fraises et spécialités',  tagEN: 'Strawberry wines & specialties',     bioFR: 'Vins de fruits, hypocras et mistelles du Domaine Mont Vezeau.', bioEN: 'Fruit wines, hypocras and mistelles from Domaine Mont Vezeau.', href: 'http://www.domainemont-vezeau.com/', image: '/wix/marche/1d8aca4a.jpg' , years: [2025] },
  { id: 'confections-zad',   name: 'Confections ZAD',       tier: 'marche', contact: 'Zoé Asselin',      email: 'zad@confections.example.ca', category: 'Costumes',    tagFR: 'Confections d’époque',                  tagEN: 'Period costuming',                    bioFR: 'Costumes d’époque sur mesure pour reconstitution et scène.', bioEN: 'Period costumes made to measure for reenactment and stage.', image: '/wix/marche/b4f50022.webp' , years: [2025] },
];

/* ─── Boutique Digitale ───────────────────────────────────────────────
   Online-only partners. Get a promo code reveal animation on the page. */
export const DIGITAL_VENDORS: MarcheKiosk[] = [
  {
    id: 'julie-chantal',
    name: 'Julie-Chantal',
    tier: 'digital',
    contact: 'Julie-Chantal Dubreuil',
    email: 'julie.chantal@example.ca',
    category: 'Patrons de costumes médiévaux',
    tagFR: 'Patrons de couture & outils numériques',
    tagEN: 'Sewing patterns & digital tools',
    bioFR:
      'Pour une immersion complète, confectionnez votre propre costume médiéval. Julie-Chantal propose une variété de patrons de couture et d’autres outils numériques pour vous aider à habiller toute la famille.',
    bioEN:
      'For full immersion, sew your own medieval garb. Julie-Chantal offers a variety of sewing patterns and digital tools to help you costume the whole family.',
    image: '/wix/marche/c8a35365.jpg',
    href: 'https://juliechantal.com/',
    promo: 'FMM20',
  },
];

/** All kiosks flattened, handy for CRM seed + counts. */
export const ALL_VENDORS: MarcheKiosk[] = [
  ...PREMIUM_VENDORS,
  ...MARCHE_VENDORS,
  ...DIGITAL_VENDORS,
];
