// ─── Le sondage de retour de l'édition 2026 ─────────────────────────
// Alex, 2026-09-28 : un bouton évident sur la page de remerciements,
// et des questions d'une seule phrase chacune. Les réponses vont dans
// `sondageRetour2026` (création seulement, lecture par l'équipe).

export type TypeQuestion = 'note' | 'choix' | 'plusieurs' | 'classement' | 'texte' | 'court';

export interface QuestionSondage {
  id: string;
  type: TypeQuestion;
  FR: string;
  EN: string;
  /** `preciser` ouvre la case « Précisez », comme le choix Autre. */
  options?: { id: string; FR: string; EN: string; preciser?: boolean }[];
  facultatif?: boolean;
  /** Le titre de la partie qui commence à cette question. */
  section?: { FR: string; EN: string };
}

/** L'option qui ouvre une case pour préciser. */
export const AUTRE = 'autre';

export const QUESTIONS_SONDAGE: QuestionSondage[] = [
  { id: 'role', type: 'choix',
    section: { FR: 'Votre fin de semaine', EN: 'Your weekend' },
    FR: 'À quel titre étiez-vous au festival ?',
    EN: 'In what capacity were you at the festival?',
    options: [
      { id: 'visiteur', FR: 'Comme visiteur ou visiteuse', EN: 'As a visitor' },
      { id: 'exposant', FR: 'Comme exposant ou artisan', EN: 'As an exhibitor or artisan' },
      { id: 'artiste', FR: 'Comme artiste ou membre d’une troupe', EN: 'As an artist or troupe member' },
      { id: 'benevole', FR: 'Comme bénévole', EN: 'As a volunteer' },
      { id: AUTRE, FR: 'Autrement', EN: 'Another way' },
    ] },
  { id: 'premiereVisite', type: 'choix',
    FR: 'Était-ce votre première visite au Festival Médiéval de Montpellier ?',
    EN: 'Was this your first visit to the Festival Médiéval de Montpellier?',
    options: [
      { id: 'oui', FR: 'Oui, c’était la première fois', EN: 'Yes, it was my first time' },
      { id: 'non', FR: 'Non, je connaissais déjà le festival', EN: 'No, I had come before' },
    ] },
  { id: 'jours', type: 'plusieurs',
    FR: 'Quelles journées avez-vous passées au festival ?',
    EN: 'Which days did you spend at the festival?',
    options: [
      { id: 'vendredi', FR: 'Vendredi', EN: 'Friday' },
      { id: 'samedi', FR: 'Samedi', EN: 'Saturday' },
      { id: 'dimanche', FR: 'Dimanche', EN: 'Sunday' },
    ] },
  { id: 'activitesPreferees', type: 'plusieurs',
    FR: 'Quelles activités avez-vous le plus appréciées ?',
    EN: 'Which activities did you enjoy the most?',
    options: [
      { id: 'joutes', FR: 'Les joutes équestres', EN: 'The jousts on horseback' },
      { id: 'escrime', FR: 'L’escrime et les combats', EN: 'Fencing and combat' },
      { id: 'tournois', FR: 'Les tournois', EN: 'The tournaments' },
      { id: 'vikings', FR: 'Le campement viking', EN: 'The Viking camp' },
      { id: 'spectacles', FR: 'Les spectacles et la musique', EN: 'The shows and the music' },
      { id: 'soiree', FR: 'La soirée dansante', EN: 'The dance party' },
      { id: 'demonstrations', FR: 'La forge et les démonstrations', EN: 'The forge and the demonstrations' },
      { id: 'villagePaysan', FR: 'Le village paysan et les sorcières', EN: 'The peasant village and the witches' },
      { id: 'marche', FR: 'Le marché des artisans', EN: 'The artisans’ market' },
      { id: 'jeunesse', FR: 'L’espace jeunesse', EN: 'The youth space' },
      { id: 'nourriture', FR: 'L’offre de nourriture', EN: 'The food offering' },
      { id: AUTRE, FR: 'Autre chose', EN: 'Something else' },
    ] },
  { id: 'groupesPreferes', type: 'plusieurs',
    FR: 'Quels groupes avez-vous préférés sur scène ?',
    EN: 'Which bands did you enjoy most on stage?',
    options: [
      { id: 'skarazula', FR: 'Skarazula', EN: 'Skarazula' },
      { id: 'harfang', FR: 'L’Harfang', EN: 'L’Harfang' },
      { id: 'troupeCaravane', FR: 'Troupe Caravane (Fuego Bohemio)', EN: 'Troupe Caravane (Fuego Bohemio)' },
      { id: 'klezmer', FR: 'L’Ensemble Klezmer de Sainte-Nigoune', EN: 'L’Ensemble Klezmer de Sainte-Nigoune' },
      { id: 'bicoasis', FR: 'BicOasis', EN: 'BicOasis' },
      { id: 'trifolys', FR: 'Trifolys', EN: 'Trifolys' },
      { id: 'svarica', FR: 'Svarica', EN: 'Svarica' },
      { id: 'nochesBohemias', FR: 'Las Noches Bohemias', EN: 'Las Noches Bohemias' },
      { id: 'alhambra', FR: 'Alhambra', EN: 'Alhambra' },
      { id: 'aucun', FR: 'Je n’ai pas vu de groupe', EN: 'I did not see any band' },
      { id: AUTRE, FR: 'Un autre spectacle', EN: 'Another show' },
    ] },
  { id: 'noteActivites', type: 'note',
    FR: 'Comment avez-vous trouvé les activités dans leur ensemble ?',
    EN: 'How did you find the activities overall?' },
  { id: 'noteNourriture', type: 'note',
    FR: 'Comment avez-vous trouvé la nourriture et les boissons du village ?',
    EN: 'How did you find the village’s food and drinks?' },
  { id: 'noteThematique', type: 'note',
    FR: 'Comment avez-vous trouvé la thématique Caravanes et Saltimbanques ?',
    EN: 'How did you find the Caravans and Mountebanks theme?' },
  { id: 'themesVotes', type: 'plusieurs',
    section: { FR: 'Les prochaines éditions', EN: 'The next editions' },
    FR: 'Pour quelles thématiques voteriez-vous aux prochaines éditions ?',
    EN: 'Which themes would you vote for at the next editions?',
    options: [
      { id: 'pirates', FR: 'Pirates et corsaires', EN: 'Pirates and privateers' },
      { id: 'celtes', FR: 'Celtes et druides', EN: 'Celts and druids' },
      { id: 'routeSoie', FR: 'La Route de la soie', EN: 'The Silk Road' },
      { id: 'chevaliers', FR: 'Chevaliers', EN: 'Knights' },
      { id: 'magie', FR: 'Magie et alchimie', EN: 'Magic and alchemy' },
      { id: 'vikings', FR: 'Les Vikings, encore !', EN: 'The Vikings, again!' },
      { id: 'caravanes', FR: 'Caravanes et Saltimbanques, encore !', EN: 'Caravans and Mountebanks, again!' },
      { id: 'croisades', FR: 'Les Croisades', EN: 'The Crusades' },
      { id: 'templiers', FR: 'Templiers et ordres secrets', EN: 'Templars and secret orders' },
      { id: 'robin', FR: 'Robin des Bois et les hors-la-loi', EN: 'Robin Hood and the outlaws' },
      { id: 'invasions', FR: 'Les invasions barbares', EN: 'The barbarian invasions' },
      { id: 'marchands', FR: 'Marchands et bateaux', EN: 'Merchants and ships' },
      { id: 'paysans', FR: 'Paysans', EN: 'Peasants' },
      { id: 'fous', FR: 'La Fête des fous et le carnaval', EN: 'The Feast of Fools and carnival' },
      { id: 'legendes', FR: 'Contes et légendes d’ici', EN: 'Local tales and legends' },
      { id: AUTRE, FR: 'Autre', EN: 'Other' },
    ] },
  { id: 'budget', type: 'classement',
    FR: 'Selon vous, où devrions-nous concentrer nos efforts et nos ressources l’an prochain ? Glissez en haut ce qui compte le plus.',
    EN: 'In your view, where should we focus our efforts and resources next year? Drag what matters most to the top.',
    options: [
      { id: 'spectacles', FR: 'Les spectacles', EN: 'The shows' },
      { id: 'cachets', FR: 'Le cachet des artistes', EN: 'Artists’ fees' },
      { id: 'programmation', FR: 'La programmation', EN: 'The programming' },
      { id: 'sonEclairage', FR: 'La technique de son et d’éclairage', EN: 'Sound and lighting' },
      { id: 'internet', FR: 'Internet sur le site', EN: 'Internet on site' },
      { id: 'siteWeb', FR: 'Le site internet', EN: 'The website' },
      { id: 'remuneration', FR: 'Payer les bénévoles et les organisateurs', EN: 'Paying volunteers and organizers' },
      { id: 'videoPhoto', FR: 'Les vidéos et les photos', EN: 'Videos and photos' },
      { id: 'publicite', FR: 'La publicité', EN: 'Advertising' },
      { id: 'decorum', FR: 'Les installations permanentes, les décorations et le décorum', EN: 'Permanent structures, decorations and decorum' },
      { id: 'terrain', FR: 'L’achat d’un terrain médiéval', EN: 'Buying a medieval site' },
      { id: 'jeunesse', FR: 'Le village jeunesse', EN: 'The youth village' },
      { id: 'villagePaysan', FR: 'Le village paysan', EN: 'The peasant village' },
      { id: 'nourriture', FR: 'L’offre de nourriture', EN: 'The food offering' },
      { id: 'bar', FR: 'Le bar', EN: 'The bar' },
      { id: 'sanitaires', FR: 'Les installations sanitaires', EN: 'Washroom facilities' },
      { id: 'camping', FR: 'Le camping', EN: 'The campground' },
      { id: 'stationnement', FR: 'Le stationnement et les navettes', EN: 'Parking and shuttles' },
      { id: 'accessibilite', FR: 'L’accessibilité du site', EN: 'Site accessibility' },
      { id: 'securite', FR: 'La sécurité et les premiers soins', EN: 'Safety and first aid' },
      { id: 'ombre', FR: 'L’ombre, les abris et les places assises', EN: 'Shade, shelters and seating' },
      { id: AUTRE, FR: 'Autre chose', EN: 'Something else' },
    ] },
  { id: 'suggestions', type: 'texte', facultatif: true,
    FR: 'Quelles suggestions aimeriez-vous faire à l’équipe pour la suite ?',
    EN: 'What suggestions would you like to make to the team for what comes next?' },
  { id: 'noteApprentissage', type: 'note',
    section: { FR: 'Le bilan', EN: 'The verdict' },
    FR: 'Comment évaluez-vous ce que le festival vous a fait découvrir de l’histoire et du patrimoine ?',
    EN: 'How would you rate what the festival taught you about history and heritage?' },
  { id: 'noteAcces', type: 'note',
    FR: 'Comment avez-vous trouvé l’accès au site, du stationnement à la circulation entre les zones ?',
    EN: 'How did you find access to the site, from parking to moving between areas?' },
  { id: 'noteSiteWeb', type: 'note',
    FR: 'Comment avez-vous trouvé le site internet du festival ?',
    EN: 'How did you find the festival’s website?' },
  { id: 'noteFacebook', type: 'note', facultatif: true,
    FR: 'Comment avez-vous trouvé la page Facebook du festival ?',
    EN: 'How did you find the festival’s Facebook page?' },
  { id: 'noteServiceClient', type: 'note',
    FR: 'Comment avez-vous trouvé l’accueil et le service aux festivaliers, de la billetterie aux réponses à vos questions ?',
    EN: 'How did you find the welcome and service to festivalgoers, from ticketing to answers to your questions?' },
  { id: 'noteCamping', type: 'note', facultatif: true,
    FR: 'Si vous avez campé sur le site, comment avez-vous trouvé le camping ?',
    EN: 'If you camped on site, how did you find the campground?' },
  { id: 'noteGlobale', type: 'note',
    FR: 'Quelle note donnez-vous à l’édition 2026 dans son ensemble ?',
    EN: 'How would you rate the 2026 edition overall?' },
  { id: 'ameliorer', type: 'texte', facultatif: true,
    FR: 'Qu’est-ce que l’équipe devrait améliorer en premier pour la prochaine édition ?',
    EN: 'What should the team improve first for the next edition?' },
  { id: 'recommander', type: 'choix',
    FR: 'Recommanderiez-vous le festival à vos proches ?',
    EN: 'Would you recommend the festival to people close to you?',
    options: [
      { id: 'certainement', FR: 'Certainement', EN: 'Definitely' },
      { id: 'probablement', FR: 'Probablement', EN: 'Probably' },
      { id: 'peutEtre', FR: 'Peut-être', EN: 'Maybe' },
      { id: 'non', FR: 'Non', EN: 'No' },
    ] },
  { id: 'benevolat', type: 'choix',
    FR: 'Aimeriez-vous vous joindre aux bénévoles de la prochaine édition ?',
    EN: 'Would you like to join the volunteers for the next edition?',
    options: [
      { id: 'oui', FR: 'Oui', EN: 'Yes' },
      { id: 'peutEtre', FR: 'Peut-être', EN: 'Maybe' },
      { id: 'non', FR: 'Non', EN: 'No' },
    ] },
  { id: 'revenir', type: 'choix',
    FR: 'Pensez-vous revenir au festival l’an prochain ?',
    EN: 'Do you plan to come back to the festival next year?',
    options: [
      { id: 'oui', FR: 'Oui', EN: 'Yes' },
      { id: 'peutetre', FR: 'Peut-être', EN: 'Maybe' },
      { id: 'non', FR: 'Non', EN: 'No' },
    ] },
  { id: 'decouverte', type: 'choix',
    FR: 'Comment avez-vous entendu parler du festival ?',
    EN: 'How did you hear about the festival?',
    options: [
      { id: 'facebook', FR: 'Facebook', EN: 'Facebook' },
      { id: 'instagram', FR: 'Instagram', EN: 'Instagram' },
      { id: 'bouche', FR: 'Le bouche-à-oreille', EN: 'Word of mouth' },
      { id: 'google', FR: 'Une recherche sur Google', EN: 'A Google search' },
      { id: 'teleRadio', FR: 'La télé ou la radio', EN: 'TV or radio' },
      { id: 'journaux', FR: 'Les journaux', EN: 'Newspapers' },
      { id: 'affiche', FR: 'Une affiche', EN: 'A poster' },
      { id: 'deja', FR: 'J’y viens déjà chaque année', EN: 'I already come every year' },
      { id: AUTRE, FR: 'Autrement', EN: 'Another way' },
    ] },
  { id: 'provenance', type: 'choix',
    section: { FR: 'Pour mieux vous connaître', EN: 'Getting to know you' },
    FR: 'De quelle région arriviez-vous au festival ?',
    EN: 'Where did you travel from to the festival?',
    options: [
      { id: 'petiteNation', FR: 'De la Petite-Nation', EN: 'From Petite-Nation' },
      { id: 'outaouais', FR: 'D’ailleurs en Outaouais', EN: 'From elsewhere in Outaouais', preciser: true },
      { id: 'laurentides', FR: 'Des Laurentides', EN: 'From the Laurentians' },
      { id: 'montreal', FR: 'De Montréal ou de Laval', EN: 'From Montreal or Laval' },
      { id: 'ontario', FR: 'D’Ottawa ou de l’Ontario', EN: 'From Ottawa or Ontario' },
      { id: 'quebec', FR: 'D’ailleurs au Québec', EN: 'From elsewhere in Quebec', preciser: true },
      { id: AUTRE, FR: 'D’ailleurs', EN: 'From elsewhere' },
    ] },
  { id: 'distance', type: 'choix',
    FR: 'Quelle distance avez-vous parcourue pour venir au festival ?',
    EN: 'How far did you travel to come to the festival?',
    options: [
      { id: 'm40', FR: 'Moins de 40 km', EN: 'Under 40 km' },
      { id: '40-80', FR: 'De 40 à 80 km', EN: '40 to 80 km' },
      { id: '80-160', FR: 'De 80 à 160 km', EN: '80 to 160 km' },
      { id: '160-300', FR: 'De 160 à 300 km', EN: '160 to 300 km' },
      { id: '300+', FR: 'Plus de 300 km', EN: 'Over 300 km' },
    ] },
  { id: 'motif', type: 'choix',
    FR: 'Le festival était-il la raison principale de votre venue dans la région ?',
    EN: 'Was the festival the main reason for your trip to the region?',
    options: [
      { id: 'principale', FR: 'Oui, la raison principale', EN: 'Yes, the main reason' },
      { id: 'parmiAutres', FR: 'Une raison parmi d’autres', EN: 'One reason among others', preciser: true },
      { id: 'dejaLa', FR: 'Non, j’étais déjà dans la région', EN: 'No, I was already in the region' },
    ] },
  { id: 'codePostal', type: 'court', facultatif: true,
    FR: 'Quels sont les trois premiers caractères de votre code postal ?',
    EN: 'What are the first three characters of your postal code?' },
  { id: 'age', type: 'choix',
    FR: 'Dans quel groupe d’âge êtes-vous ?',
    EN: 'Which age group are you in?',
    options: [
      { id: 'm18', FR: 'Moins de 18 ans', EN: 'Under 18' },
      { id: '18', FR: '18 à 24 ans', EN: '18 to 24' },
      { id: '25', FR: '25 à 34 ans', EN: '25 to 34' },
      { id: '35', FR: '35 à 44 ans', EN: '35 to 44' },
      { id: '45', FR: '45 à 54 ans', EN: '45 to 54' },
      { id: '55', FR: '55 à 64 ans', EN: '55 to 64' },
      { id: '65', FR: '65 ans et plus', EN: '65 and over' },
    ] },
  { id: 'groupe', type: 'choix',
    FR: 'Avec qui avez-vous fait la visite ?',
    EN: 'Who did you visit with?',
    options: [
      { id: 'solo', FR: 'En solo', EN: 'On my own' },
      { id: 'couple', FR: 'En couple', EN: 'As a couple' },
      { id: 'famille', FR: 'En famille, avec des enfants', EN: 'As a family, with children' },
      { id: 'amis', FR: 'Entre amis', EN: 'With friends' },
      { id: 'organise', FR: 'Avec un groupe organisé', EN: 'With an organized group' },
      { id: AUTRE, FR: 'Autrement', EN: 'Another way' },
    ] },
  { id: 'taille', type: 'choix',
    FR: 'Combien de personnes comptait votre groupe, vous compris ?',
    EN: 'How many people were in your group, yourself included?',
    options: [
      { id: '1', FR: '1', EN: '1' }, { id: '2', FR: '2', EN: '2' },
      { id: '3-4', FR: '3 ou 4', EN: '3 or 4' }, { id: '5-6', FR: '5 ou 6', EN: '5 or 6' },
      { id: '7+', FR: '7 et plus', EN: '7 or more' },
    ] },
  { id: 'hebergement', type: 'choix',
    FR: 'Où avez-vous dormi pendant le festival ?',
    EN: 'Where did you sleep during the festival?',
    options: [
      { id: 'maison', FR: 'À la maison, sans nuitée', EN: 'At home, no overnight stay' },
      { id: 'campingFestival', FR: 'Au camping du festival', EN: 'At the festival campground' },
      { id: 'region', FR: 'Dans un hôtel, un gîte ou une auberge de la région', EN: 'In a hotel, B&B or inn in the region' },
      { id: 'campingRegion', FR: 'Dans un autre camping de la région', EN: 'At another campground in the region', preciser: true },
      { id: 'proches', FR: 'Chez des proches', EN: 'With family or friends' },
      { id: AUTRE, FR: 'Ailleurs', EN: 'Somewhere else' },
    ] },
  { id: 'nuitees', type: 'choix',
    FR: 'Combien de nuits avez-vous passées dans la région pour le festival ?',
    EN: 'How many nights did you spend in the region for the festival?',
    options: [
      { id: '0', FR: 'Aucune', EN: 'None' },
      { id: '1', FR: 'Une', EN: 'One' },
      { id: '2', FR: 'Deux', EN: 'Two' },
      { id: '3+', FR: 'Trois ou plus', EN: 'Three or more' },
    ] },
  { id: 'depensesSite', type: 'choix',
    FR: 'Combien votre groupe a-t-il dépensé sur le site, sans compter les billets ?',
    EN: 'How much did your group spend on site, not counting tickets?',
    options: [
      { id: '0-50', FR: 'Moins de 50 $', EN: 'Under $50' },
      { id: '50-100', FR: 'De 50 $ à 100 $', EN: '$50 to $100' },
      { id: '100-200', FR: 'De 100 $ à 200 $', EN: '$100 to $200' },
      { id: '200-400', FR: 'De 200 $ à 400 $', EN: '$200 to $400' },
      { id: '400+', FR: 'Plus de 400 $', EN: 'Over $400' },
    ] },
  { id: 'depensesRegion', type: 'choix',
    FR: 'Combien votre groupe a-t-il dépensé ailleurs dans la région pendant le séjour, en hébergement, au restaurant, en essence ou à l’épicerie ?',
    EN: 'How much did your group spend elsewhere in the region during the stay, on lodging, restaurants, gas or groceries?',
    options: [
      { id: '0', FR: 'Rien', EN: 'Nothing' },
      { id: '0-50', FR: 'Moins de 50 $', EN: 'Under $50' },
      { id: '50-150', FR: 'De 50 $ à 150 $', EN: '$50 to $150' },
      { id: '150-300', FR: 'De 150 $ à 300 $', EN: '$150 to $300' },
      { id: '300+', FR: 'Plus de 300 $', EN: 'Over $300' },
    ] },
  { id: 'langue', type: 'choix',
    FR: 'Quelle langue parlez-vous le plus souvent à la maison ?',
    EN: 'Which language do you speak most often at home?',
    options: [
      { id: 'fr', FR: 'Le français', EN: 'French' },
      { id: 'en', FR: 'L’anglais', EN: 'English' },
      { id: 'deux', FR: 'Les deux', EN: 'Both' },
      { id: AUTRE, FR: 'Une autre langue', EN: 'Another language' },
    ] },
  { id: 'motEquipe', type: 'texte', facultatif: true,
    FR: 'Voulez-vous laisser un mot aux bénévoles et à l’équipe ?',
    EN: 'Would you like to leave a word for the volunteers and the team?' },
];

/** Les Montpellois versés à qui termine le sondage, une fois par compte
 *  (Alex, 2026-09-28). Le montant vit aussi dans functions/index.js. */
export const BONUS_SONDAGE = 30;

export const SONDAGE_CHEMIN_FR = '/sondage';
export const SONDAGE_CHEMIN_EN = '/en/survey';

/** Les questions à remplir pour toucher le bonus : toutes celles qui ne
 *  portent pas la mention « facultatif ». La même liste vit dans
 *  functions/index.js (sondageRetourBonus), qui a le dernier mot. */
export const QUESTIONS_REQUISES = QUESTIONS_SONDAGE.filter((q) => !q.facultatif).map((q) => q.id);
